Repository qiniu/api.v7, pull requests merged in 2020-11, with the labels that each got.

#247 修复 CI 错误
  Makefile
  client/client.go
  storage/pfop_test.go
Labels: approved, size/M

#250 LINK-1674 update qvs go-sdk
  qvs/device.go
  qvs/device_test.go
  qvs/manager_test.go
  qvs/namespace.go
  qvs/record.go
  qvs/record_test.go
  qvs/stats.go
  qvs/stats_test.go
  qvs/stream.go
  qvs/stream_test.go
  qvs/template.go
  qvs/template_test.go
Labels: size/L

#251 尝试修复 CI 可能因为上传超时而失败的问题
  storage/upload.go
Labels: approved, size/XS

#237 非 200 的 2xx 响应现在也被认为是成功的响应，因为 298 代表部分批量操作成功
  .travis.yml
  client/client.go
  storage/bucket_test.go
Labels: approved, size/M
