Repository qiniu/api.v7, pull requests merged in 2020-09, with the labels that each got.

#230 LINK-1489 update qvs-sdk
  qvs/device.go
  qvs/device_test.go
  qvs/namespace.go
  qvs/namespace_test.go
  qvs/stream.go
  qvs/stream_test.go
  qvs/template_test.go
Labels: size/L

#225 分片上传 v2
  .travis.yml
  Makefile
  conf/conf.go
  go.mod
  storage/base64_upload.go
  storage/bucket_test.go
  storage/form_upload.go
  storage/resume_base.go
  storage/resume_upload.go
  storage/resume_upload_test.go
  storage/resume_uploader.go
  storage/resume_uploader_apis.go
  storage/resume_uploader_base.go
  storage/resume_uploader_deprecated.go
  storage/resume_uploader_test.go
  storage/resume_uploader_v2.go
  storage/resume_uploader_v2_test.go
  storage/upload.go
  storage/uploader_base.go
  storage/worker_test.go
Labels: approved, lgtm, size/XXL

#231 qvs 更新go sdk
  qvs/device.go
  qvs/device_test.go
  qvs/namespace.go
  qvs/namespace_test.go
  qvs/stream.go
  qvs/stream_test.go
  qvs/template_test.go
Labels: approved, size/L

#233 Revert "分片上传 v2"
  .travis.yml
  Makefile
  conf/conf.go
  go.mod
  storage/base64_upload.go
  storage/bucket_test.go
  storage/form_upload.go
  storage/resume_base.go
  storage/resume_upload.go
  storage/resume_upload_test.go
  storage/resume_uploader.go
  storage/resume_uploader_apis.go
  storage/resume_uploader_base.go
  storage/resume_uploader_deprecated.go
  storage/resume_uploader_test.go
  storage/resume_uploader_v2.go
  storage/resume_uploader_v2_test.go
  storage/upload.go
  storage/uploader_base.go
  storage/worker_test.go
Labels: approved, size/XXL

#234 Update conf.go
  conf/conf.go
Labels: approved, size/XS

#235 Update CHANGELOG.md
  CHANGELOG.md
Labels: approved, size/S
